[package]
name = "xr0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2"
libc = "0.2"
peg = "0.8"

[build-dependencies]
cc = "1.0"
